version: "3.9"
name: ghost-cn-dev

services:
  ghost-mysql-cn-dev:
    image: mysql:8.0
    container_name: ghost-mysql-cn-dev
    restart: unless-stopped
    command: --port=3308 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "BESpA-cLF+2RT#8"
      MYSQL_DATABASE: db_blog_server_dev
      MYSQL_TCP_PORT: 3308
      TZ: Asia/Shanghai
    ports:
      - "3308:3308"
    volumes:
      - ghost_mysql_cn_dev_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3308 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  ghost-cn-dev:
    image: ghost:5-alpine
    container_name: ghost-cn-dev
    restart: unless-stopped
    depends_on:
      ghost-mysql-cn-dev:
        condition: service_healthy
    environment:
      NODE_ENV: production
    ports:
      - "2370:2370"
    volumes:
      - ./config.development.json:/var/lib/ghost/config.development.json
      - ghost_cn_dev_content:/var/lib/ghost/content

volumes:
  ghost_mysql_cn_dev_data:
  ghost_cn_dev_content:
