
  /** 此文件自动生成，请勿修改！所有可用的 svg name */
  export type SvgNames = 'base/rx_ic_logo'
  | 'base/rx_ic_chevron_down'
  | 'base/rx_ic_world'
  | 'base/rx_ic_menu'
  | 'menu/traffic-trade'
  | 'menu/ad-strategy'
  | 'menu/social-networks'
  | 'menu/e-commerce'
  | 'menu/affiliate-market'
  | 'menu/web-spcraping'
  | 'menu/crypto-gains'
  | 'menu/profile-template'
  | 'menu/proxy-panel'
  | 'menu/team-space'
  | 'menu/account-hub'
  | 'menu/window-sync'
  | 'base/rx_ic_check_fill'
  | 'menu/api-flow'
  | 'base/rx_ic_right'
  | 'base/rx_ic_email'
  | 'base/rx_ic_back_top'