
  /** 此文件自动生成，请勿修改！所有可用的 svg name */
  export type SvgNames = 'base/rx_ic_logo'
  | 'base/rx_ic_chrome2'
  | 'base/rx_ic_chevron_down'
  | 'base/rx_ic_world'
  | 'base/rx_ic_menu'
  | 'menu/privacy-defense'
  | 'menu/affiliate-market'
  | 'menu/web-scraping'
  | 'menu/e-commerce'
  | 'menu/social-networks'
  | 'menu/crypto-gains'
  | 'menu/traffic-trade'
  | 'menu/profile-template'
  | 'menu/ad-strategy'
  | 'menu/proxy-panel'
  | 'menu/team-space'
  | 'menu/account-hub'
  | 'menu/window-sync'
  | 'menu/api-flow'
  | 'base/rx_ic_headphone_2'
  | 'base/rx_ic_download'
  | 'base/rx_ic_roxy_chrome'
  | 'platforms/rx_os_windows'
  | 'base/rx_ic_2fa'
  | 'country/rx_flag_uk'
  | 'base/rx_ic_stack'
  | 'base/rx_ic_email'
  | 'base/rx_ic_plus'
  | 'base/rx_ic_back_top'
  | 'base/rx_ic_chrome'